name: furniture_detection
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python stabile per DL + strumenti
  - python=3.10

  # Stack scientifico
  - numpy=1.26.*
  - pandas=2.1.*
  - scikit-learn=1.3.*
  - scipy
  - matplotlib

  # OpenCV (conda, non headless per evitare conflitti ffmpeg)
  #- opencv=4.9.*

  # PyTorch CPU
  - pytorch=2.3.*
  - torchvision=0.18.*
  - torchaudio=2.3.*
  - cpuonly

  # Notebook / kernel (per Jupyter e Spyder)
  - ipykernel
  - jupyterlab          # opzionale ma comodo
  - spyder-kernels=3.0  # compatibile con Spyder 6.x

  # Utilit√†
  - tqdm
  - pillow
  - pyyaml

  # pip per pacchetti non conda
  - pip
  - pip:
      - ultralytics==8.3.209 
      # Se preferisci OpenCV headless:
      - opencv-python-headless==4.9.0.80 

      - "numpy<2"
      - "scikit-learn<1.4"
      # (rimuovi allora la riga con "opencv=" sopra)
      # TensorFlow (opzionale, solo se ti serve)
      # - tensorflow-cpu==2.13.0
